config/routes.rb
Medstore::Application.routes.draw do
  
  resources :line_items

  resources :carts

  get "store/index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy"
  resources :sessions
  resources :users
  resources :vendors
  resources :products
  root :to=>'store#index'
  match 'home' => 'products#home', :as => 'home'
  match 'delete_product' => 'products#delete_product', :as => 'delete_product', :via => :delete
  match 'search_results' => 'products#search_results', :as => 'search_results'
  match 'reports' => 'products#reports', :as => 'reports'

end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'product_name'
  before_destroy :ensure_not_referenced_by_any_line_item
  attr_accessible :btch_no, :cost_price, :expired_on, :mfd_on, :product_name, :vendor_id, :product, :remain_days, :created_at, :updated_at
  belongs_to :vendor
  has_many :line_items

  private
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base, 'Line items present')
  		return false
  	end
  end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :vendor_address, :vendor_name, :product_id, :vendor, :created_at, :updated_at
  has_many :products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  #add_breadcrumb "Home", "/products/home"
  http_basic_authenticate_with :name=>"admin", :password=>"admin"
  add_breadcrumb "Browse products", "/products", except: [:home,:reports,:welcome]
  add_breadcrumb "New Product", "/products/new", only: [:new, :create, :show]
  add_breadcrumb "Edit Product", "/products/edit", only: [:edit]
 # add_breadcrumb "Search Results", "/products/search_results", only: [:search_results]

  
  require 'date'
  def welcome
  end
  def reports
    a = Date.today
    @products = Product.all
    @exproduct = Product.where("expired_on < ?", a+30)
  end
    

  def home
    a = Date.today
    
    @products=Product.all
    
    @exproduct = Product.where("expired_on < ?", a+30)
    
    #@rd = params[:product] && params[:product][:expired_on]
    #@remain_days = params[:product][:expired_on]
  

  end
  def index
    @products = Product.all
    @products = Product.order("id").page(params[:page]).per(5)
    @vendors = Vendor.all
    #@vendors = Vendor.find(params[:id])

    # q = Product.where(params[:product_name])
    # #q = params[:product][:product_name]
    #   @search_results = Product.find(:all, :conditions => ['product_name LIKE ?', "%#{q}%"]) 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def search_results

    q = params[:product][:product_name]
    @search_results = Product.find(:all, :conditions => ['product_name LIKE ?', "%#{q}%"])
  
  end
  # GET /products/1
  # GET /products/1.json
  def show
    
    @product = Product.find(params[:id])
    @vendors = @product.vendor(:all)
    #@vendors = Vendor.find(params[:id])
    #@vendors = Vendor.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
 
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    #@product = Product.create(vendor_id: @vendor.id)
    #@vendor = Vendor.all
    #@product = @vendor.products.create(product_date :Time.now, vendor_id: @vendor.id)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
  

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
      format.js { render :layout => false }
    end
    end
    def delete_product
     #Product.destroy(params[:product])
     #@product = Product.where(params[:id])
     #@product = Product.all
     #@product.delete(params[:product_id])

     @products = Product.find(params[:product_ids])

     @products.each do |product|    
      product.destroy
      flash[:alert] = "Selected products deleted successfully.."
    end
      respond_to do |format|
        format.html {redirect_to products_url}
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :product_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_name, :class => 'text_field' %><span class="help-inline"></span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :btch_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :btch_no, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vendor, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :vendor_id,Vendor.order(:vendor_name),:id,:vendor_name, :class => 'collection_select' %>
    <%#<select name="product[vendor_id]">
    <%#<% Vendor.all.each do |vendor| %>
    <%# <option value="<%= vendor.id %>  <%#"> <%= vendor.vendor_name %></option>
    <%#<% end %>

</select>


    </div>
  </div>
  <div class="control-group">
    <%= f.label :mfd_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :mfd_on, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :expired_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :expired_on, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cost_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cost_price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/destroy.js.erb
$('.delete_prodct').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});

app/views/products/edit.html.erb
<%- model_class = @product.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/products/home.html.erb
<%# Images carousel display................................................... %>

<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <p data-target="#myCarousel" data-slide-to="0" class="active"></p>
    <p data-target="#myCarousel" data-slide-to="1"></p>
    <p data-target="#myCarousel" data-slide-to="2"></p>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><img src="pills.jpg"></div>
    <div class="item"><img src="pills1.jpg"></div>
    <div class="item"><img src="pills2.jpg"></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
    </div>
  </div>

<%# Latest products............................................................ %>

    <div class="row-fluid">
      <div class="span4">
          <pre style="background-color:#ffffff;"><b style="font-family:'tempus sans itc';color:indigo;">Latest products</b>
            <table>
            <% @products.last(5).reverse.each do |f| %>
           <tr><td style="padding-right:0px"><%= f.product_name %></td>
           </tr>
            <% end %>
        </table>
        <b style="padding-left:140px;"><%= link_to 'more...',reports_path() %></b>
        </pre>
      </div>

<%# About to expire products.....................................................%>

      <div class="span5">
          <pre style="background-color:#ffffff;"><b style="font-family:'tempus sans itc';color:indigo;">About to Expire products</b>
          <table>
          <% @exproduct.last(5).each do |p| %>
         <tr><td align="left"><%= p.product_name %></td>
        <td style="padding-left:40px;" align="right"><%= (p.expired_on-Date.today).to_i %>-days</td><tr/>
          <% end %>
      </table>
      <b style="padding-left:240px;"><%= link_to 'more..',reports_path() %></b>
      </pre>
      </div>

<%# Today's sale..................................................................%>

      <div class="span3">
        <pre style="background-color:#ffffff;"><b style="font-family:'tempus sans itc';color:indigo;">Today's sale                                                                                                                                                               </b>
        <p><em>Sales not started yet.. <br/>Please visit later..</em></p></pre>
      </div>
    </div>
</div>

app/views/products/index.html.erb
<%- model_class = Product.new.class -%>
<%- model_class = Vendor.new.class -%>
<h4 align="left"><%= "Products" %></h4>

<%# search form............................................................... %>

<div style="float:right" class="input-append">
<%= form_for Product.new, :url => "search_results" do |f| %>
<%= f.text_field :product_name, :class => "span8" %>
<%= f.submit "Search", :class => "btn btn-inverse" %>
<%#<%= f.submit"search" do %>
<%#<i class="icon-search"></i> <% end %>
<% end %>
</div>

<%# Delete all products checkbox............................................... %>

<%= form_tag delete_product_path, method: :delete do %>
<table class="table table-striped">
  <thead>
    <tr>  
      <th><%= "select" %>
      <th><%= model_class.human_attribute_name("Name") %></th>
      <th><%= model_class.human_attribute_name("Batch No") %></th>
     <%#<th><%= model_class.human_attribute_name("vendor id") %>
      <th><%= model_class.human_attribute_name("Manufacture date") %></th>
      <th><%= model_class.human_attribute_name("Expire date") %></th>
      <th><%= model_class.human_attribute_name("Price") %></th>

     <%# <th><%= model_class.human_attribute_name(:created_at) %></th> 
      <th><%=t '.actions', :default => t("helpers.action") %></th>
    </tr>
  </thead>
  <tbody>
    <% for product in @products %>
      <tr>
        <td><%= check_box_tag 'product_ids[]',product.id %></td>
        <td><%= link_to product.product_name, product_path(product) %></td>
        <td><%= product.btch_no %></td>
        <%#<td><%= link_to product.vendor_id, vendor_path(product) %>
        <td><%= product.mfd_on %></td>
        <td><%= product.expired_on %></td>
        <td><%= product.cost_price %></td>
        <%#<td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>

          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_prodct' %>
                      
                      
       </td>           
      </tr>

    <% end %>
    
    <%= submit_tag 'Delete selected',:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-small' %>

    &nbsp;
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-small' %>

    </tbody>
    </table>
    <%= submit_tag 'Delete selected',:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-small, delete_prodct', :remote => true %>    
    &nbsp;
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-small' %>


    <% end %>
  
<div class="pagination pagination-centered"><%= paginate @products %></div>

app/views/products/new.html.erb
<%- model_class = @product.class -%>
<%#<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New#{model_class.model_name.human}") %><h2>New Product</h2>
<%= render :partial => 'form' %>

app/views/products/reports.html.erb
<h4>Stock Report:</h4><br />
<div style="width:100%;">
<div style="height:300px;width:30%;float:left;">
<h5><em>All Products: ( <%= @products.count %> )</em></h5><br/>
<% @products.each do |product| %>
	<li><%= link_to product.product_name, product_path(product) %></li><br />
	<% end %>
</div>
<div style="height:300px;width:40%;float:left;">
	<h5><em>Recently added products:</em></h5><br/>
	<% @products.last(5).reverse.each do |product| %>
		<li><%= link_to product.product_name, product_path(product)  %> &nbsp; <%= product.created_at %></li><br />
		<% end %>
</div>
<div style="height:300px;width:30%;float:right;">
	<h5><em>Products expire in 30 days: ( <%= @exproduct.count %> )</em></h5><br/>
	<% @exproduct.last(5).each do |p| %>
		<li><%= link_to p.product_name, product_path(p)  %>&nbsp;(<%= (p.expired_on-Date.today).to_i %>-days)</li><br />
		<% end %>
</div>

</div>

app/views/products/search_results.html.erb
<%# Search results display........................................%>
<b>Search results:</b><br/><br/>
<% @search_results.each do |sr| %>
<li><%= link_to sr.product_name, product_path(sr) %></li><br />
<% end %>

app/views/products/show.html.erb
<table>
  <tr><td><b>Product Name:  &nbsp; </b></td>
<td><%= @product.product_name %></td></tr>
<tr><td><b>Batch Number:  &nbsp; </b></td>
<td><%= @product.btch_no %></td>
<tr><td><b>Vendor Name:  &nbsp; </b></td>
<td><%= link_to @vendors.vendor_name, vendor_path(@vendors) %></td>
<tr><td><b>Manufactured:  &nbsp; </b></td>
<td><%= @product.mfd_on %></td>
<tr><td><b>Expired on:  &nbsp;</b> </td>
<td><%= @product.expired_on %></td>
<tr><td><b>Cost Price:  &nbsp; </b></td>
<td><%= @product.cost_price %></td>
</table>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/products/welcome.html.erb
<h3>Hai this is welcome page</h3>
<h6><em> Please signin to continue</em></h6>